language: python
sudo: false
dist: trusty

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - check
    - libssl-dev
    - python3-pip
    - valgrind
    - gcc-5
    - libc++-dev

cache:
  directories:
  - $HOME/libsodium
  - $HOME/libtrezor-crypto

python:
  - "3.5"
  - "3.6"
  - "pypy3"

install:
  - pip install .[poc,dev]
  - ./travis-install-libsodium.sh
  - export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH
  - ./travis-install-libtrezor-crypto.sh
  - export LD_LIBRARY_PATH=$HOME/libtrezor-crypto:$LD_LIBRARY_PATH

script:
  - PYTHONPATH=.:$PYTHONPATH exec ./test-travis.sh

